FROM python:3

WORKDIR /app

COPY . .

RUN pip install .

ARG SESSION_STRING
ARG NAME="abot"
ARG PREFIX="./"
ARG SUDO="0"
ARG INSTALL=""

ENV SESSION_STRING ${SESSION_STRING}
ENV NAME ${NAME}
ENV PREFIX ${PREFIX}
ENV SUDO ${SUDO}
ENV INSTALL ${INSTALL}

CMD python -m abot $NAME --session="$SESSION_STRING" --sudo="$SUDO" --prefix="$PREFIX" --install="$INSTALL"
